### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Fabianurrutia** [IsaacSantxna/rucoyoffline#3]
This is an deffuscatted code from rucoy?, im trying to learn to defuscate code from .apk etc.. and i want to know that hehe, thanks

**Comment by IsaacSantxna** [comment]
Hi,

Nah this is just a little side project I worked on a while back haha
If you want to learn about deobfuscating apks, I'd recommend looking into decompiler/dissassembly tools such as apktool, dex2jar, jadx, etc
